"""
Pydantic request / response models for the server API.

Split into four sub-modules by concern:

* ``_shared`` — base primitives (``_WireModel``, ``ChatMode``,
  ``SnapshotRow``, ``CellContext``).
* ``auth`` — auth / account / admin / usage events.
* ``streams`` — streams, connectors, snapshots, blocks, client WS frames,
  transforms, market values, broadcast + pipeline time-series wire shapes.
* ``llm`` — LLM orchestration (router → intent → synthesis → critique),
  preview / commit / stored intent triplets, admin latency telemetry.

Every top-level name that ``models.py`` used to expose is re-exported
here so callers can continue to ``from server.api.models import X``.
"""

from __future__ import annotations

from server.api.models._shared import (
    CellContext,
    ChatMode,
    SnapshotRow,
    _WireModel,
)
from server.api.models.auth import (
    PASSWORD_MIN_LENGTH,
    USERNAME_PATTERN,
    AdminLlmFailureListResponse,
    AdminLlmFailureRow,
    AdminUserListResponse,
    AdminUserSummary,
    ApiKeyResponse,
    LoginRequest,
    LoginResponse,
    SignupRequest,
    UsageEventRequest,
    UserPublic,
)
from server.api.models.llm import (
    BlockCommitRequest,
    BlockCommitResponse,
    BlockConfigDict,
    BlockConfigRuntime,
    BlockPreviewRequest,
    BuildConverseRequest,
    ConfidenceLevel,
    CustomDerivation,
    CustomDerivationCritique,
    DataStreamIntent,
    DiscretionaryViewIntent,
    HeadlineIntent,
    IntakeClassification,
    IntentCategory,
    IntentOutput,
    InvestigateRequest,
    LlmFailureLogRequest,
    LlmFailureSignalType,
    LlmLatencySummaryResponse,
    LlmLatencySummaryStage,
    PositionDelta,
    PresetSelection,
    PreviewResponse,
    ProposalSnapshotRow,
    ProposedBlockPayload,
    RawIntent,
    StoredBlockIntent,
    StreamIntentResponse,
    StructuredIntent,
    SynthesisChoice,
    SynthesisOutput,
    UnitConversionDict,
)
from server.api.models.streams import (
    AdminConfigureStreamRequest,
    AggregatedTimeSeries,
    AggregateMarketValue,
    BankrollRequest,
    BankrollResponse,
    BlockConfigPayload,
    BlockListResponse,
    BlockRowResponse,
    BlockTimeSeries,
    ClientWsAck,
    ClientWsConnectorInputFrame,
    ClientWsError,
    ClientWsInboundFrame,
    ClientWsMarketValueFrame,
    ClientWsOutboundFrame,
    ConnectorCatalogResponse,
    ConnectorInputFieldSchema,
    ConnectorInputRequest,
    ConnectorInputResponse,
    ConnectorInputRow,
    ConnectorParamSchema,
    ConnectorSchema,
    ConnectorStateSummary,
    CreateStreamRequest,
    CurrentAggregatedDecomposition,
    CurrentBlockDecomposition,
    CurrentDecomposition,
    DataStream,
    DeleteMarketValueResponse,
    DesiredPosition,
    GlobalContext,
    ManualBlockRequest,
    MarketValueEntry,
    MarketValueListResponse,
    MarketValueMismatchAlert,
    PipelineContributionsResponse,
    PipelineDimensionsResponse,
    PipelineTimeSeriesResponse,
    PositionsSinceResponse,
    ServerPayload,
    SetMarketValueRequest,
    SetStreamActiveRequest,
    SilentStreamAlert,
    SnapshotRequest,
    SnapshotResponse,
    SpaceSeries,
    StreamKeyTimeseries,
    StreamListResponse,
    StreamResponse,
    StreamStateResponse,
    StreamTimeseriesPoint,
    StreamTimeseriesResponse,
    TimeSeriesDimension,
    TransformConfigRequest,
    TransformListResponse,
    TransformParamResponse,
    TransformResponse,
    TransformStepResponse,
    UnregisteredPushAttempt,
    UpdateBlockRequest,
    UpdateCard,
    UpdateStreamRequest,
    ZeroPositionDiagnostic,
    ZeroPositionDiagnosticsResponse,
    ZeroPositionReason,
)

__all__ = [
    # _shared
    "CellContext",
    "ChatMode",
    "SnapshotRow",
    "_WireModel",
    # auth
    "AdminLlmFailureListResponse",
    "AdminLlmFailureRow",
    "AdminUserListResponse",
    "AdminUserSummary",
    "ApiKeyResponse",
    "LoginRequest",
    "LoginResponse",
    "PASSWORD_MIN_LENGTH",
    "SignupRequest",
    "USERNAME_PATTERN",
    "UsageEventRequest",
    "UserPublic",
    # llm
    "BlockCommitRequest",
    "BlockCommitResponse",
    "BlockConfigDict",
    "BlockConfigRuntime",
    "BlockPreviewRequest",
    "BuildConverseRequest",
    "ConfidenceLevel",
    "CustomDerivation",
    "CustomDerivationCritique",
    "DataStreamIntent",
    "DiscretionaryViewIntent",
    "HeadlineIntent",
    "IntakeClassification",
    "IntentCategory",
    "IntentOutput",
    "InvestigateRequest",
    "LlmFailureLogRequest",
    "LlmFailureSignalType",
    "LlmLatencySummaryResponse",
    "LlmLatencySummaryStage",
    "PositionDelta",
    "PresetSelection",
    "PreviewResponse",
    "ProposalSnapshotRow",
    "ProposedBlockPayload",
    "RawIntent",
    "StoredBlockIntent",
    "StreamIntentResponse",
    "StructuredIntent",
    "SynthesisChoice",
    "SynthesisOutput",
    "UnitConversionDict",
    # streams
    "AdminConfigureStreamRequest",
    "AggregatedTimeSeries",
    "AggregateMarketValue",
    "BankrollRequest",
    "BankrollResponse",
    "BlockConfigPayload",
    "BlockListResponse",
    "BlockRowResponse",
    "BlockTimeSeries",
    "ClientWsAck",
    "ClientWsConnectorInputFrame",
    "ClientWsError",
    "ClientWsInboundFrame",
    "ClientWsMarketValueFrame",
    "ClientWsOutboundFrame",
    "ConnectorCatalogResponse",
    "ConnectorInputFieldSchema",
    "ConnectorInputRequest",
    "ConnectorInputResponse",
    "ConnectorInputRow",
    "ConnectorParamSchema",
    "ConnectorSchema",
    "ConnectorStateSummary",
    "CreateStreamRequest",
    "CurrentAggregatedDecomposition",
    "CurrentBlockDecomposition",
    "CurrentDecomposition",
    "DataStream",
    "DeleteMarketValueResponse",
    "DesiredPosition",
    "GlobalContext",
    "ManualBlockRequest",
    "MarketValueEntry",
    "MarketValueListResponse",
    "MarketValueMismatchAlert",
    "PipelineContributionsResponse",
    "PipelineDimensionsResponse",
    "PipelineTimeSeriesResponse",
    "PositionsSinceResponse",
    "ServerPayload",
    "SetMarketValueRequest",
    "SetStreamActiveRequest",
    "SilentStreamAlert",
    "SnapshotRequest",
    "SnapshotResponse",
    "SpaceSeries",
    "StreamKeyTimeseries",
    "StreamListResponse",
    "StreamResponse",
    "StreamStateResponse",
    "StreamTimeseriesPoint",
    "StreamTimeseriesResponse",
    "TimeSeriesDimension",
    "TransformConfigRequest",
    "TransformListResponse",
    "TransformParamResponse",
    "TransformResponse",
    "TransformStepResponse",
    "UnregisteredPushAttempt",
    "UpdateBlockRequest",
    "UpdateCard",
    "UpdateStreamRequest",
    "ZeroPositionDiagnostic",
    "ZeroPositionDiagnosticsResponse",
    "ZeroPositionReason",
]
