"use client";

import { Zap, Brain, TrendingUp } from "lucide-react";
import { ReactNode } from "react";

// ============================================================
// Derivation table data
// ============================================================

interface DerivationRow {
  step: number | string;
  logic: string;
  multiplier: string;
  annual: string;
  highlight?: boolean;
  bold?: boolean;
}

const ROWS: DerivationRow[] = [
  { step: 1, logic: "Human Baseline", multiplier: "Citadel Trader Total Comp", annual: "$700,000" },
  { step: 2, logic: "Revenue Conversion", multiplier: "\u00d7 2.5 (40% Wage-to-Revenue Ratio)", annual: "$1,750,000" },
  { step: 3, logic: "Task Allocation", multiplier: "\u00d7 20% (Position Management Focus)", annual: "$350,000" },
  { step: 4, logic: "Automation Efficiency", multiplier: "\u00d7 95% (Systematic Logic Capture)", annual: "$332,500" },
  { step: 5, logic: "Intraday Coverage", multiplier: "\u00d7 4.0 (24hrs vs. 6hr Trading Days)", annual: "$1,330,000" },
  { step: 6, logic: "Calendar Coverage", multiplier: "\u00d7 1.45 (365 days vs. 252 days)", annual: "$1,928,500" },
  { step: 7, logic: "Cognitive Bandwidth", multiplier: "\u00d7 2.0 (Parallelism / Speed / Accuracy / Perfect Memory)", annual: "$3,857,000", highlight: true },
  { step: 8, logic: "Scale Adjustment", multiplier: "\u00d7 30% (Gravity vs. Citadel Margin)", annual: "$1,157,100", highlight: true },
  { step: 9, logic: "Required ROI", multiplier: "\u00f7 2.5 (40% Wage-to-Revenue Ratio)", annual: "$462,840", bold: true },
  { step: 10, logic: "Pilot Partnership Rate", multiplier: "~50% Discount", annual: "$240,000", bold: true },
];

// ============================================================
// Strategic summary bullets
// ============================================================

interface SummaryItem {
  icon: ReactNode;
  title: string;
  description: string;
}

const SUMMARY: SummaryItem[] = [
  {
    icon: <Zap className="h-4 w-4" />,
    title: "Zero Profit Share",
    description: "The firm retains 100% of the incremental profits generated by the engine.",
  },
  {
    icon: <Brain className="h-4 w-4" />,
    title: "Institutionalized Wisdom",
    description: "Converts individual trader intuition into a permanent, 24/7 firm asset.",
  },
  {
    icon: <TrendingUp className="h-4 w-4" />,
    title: "Scalable Logic",
    description: "As scale grows, the licensing fee remains flat, significantly increasing net ROI over time.",
  },
];

// ============================================================
// Main slide
// ============================================================

export function ValuationPricingSlide() {
  return (
    <div className="flex flex-col items-center gap-8 w-full max-w-3xl mx-auto">
      <p className="text-muted-foreground text-sm leading-relaxed text-center max-w-lg">
        Monthly licensing fee derived from institutional human-capital
        benchmarks, adjusted for systematic efficiency multipliers.
      </p>

      {/* ── Derivation Table ── */}
      <div className="w-full rounded-xl border border-muted overflow-hidden">
        {/* Header */}
        <div className="grid grid-cols-[44px_140px_1fr_120px] bg-accent/40">
          <div className="px-3 py-2.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
            #
          </div>
          <div className="px-3 py-2.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground border-l border-muted">
            Logic
          </div>
          <div className="px-3 py-2.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground border-l border-muted">
            Multiplier / Calculation
          </div>
          <div className="px-3 py-2.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground border-l border-muted text-right">
            Annual (USD)
          </div>
        </div>

        {/* Rows */}
        {ROWS.map((row, i) => (
          <div
            key={row.step}
            className={`grid grid-cols-[44px_140px_1fr_120px] border-t border-muted transition-colors ${
              row.highlight
                ? "bg-[var(--brand)]/10"
                : ""
            }`}
          >
            <div
              className={`px-3 py-2.5 text-xs tabular-nums ${
                row.highlight ? "text-[var(--brand)] font-bold" : "text-muted-foreground"
              }`}
            >
              {row.step}
            </div>
            <div
              className={`px-3 py-2.5 text-xs border-l border-muted ${
                row.highlight
                  ? "text-[var(--brand)] font-semibold"
                  : row.bold
                  ? "font-semibold text-foreground"
                  : "text-foreground/90"
              }`}
            >
              {row.logic}
            </div>
            <div
              className={`px-3 py-2.5 text-xs border-l border-muted ${
                row.highlight ? "text-[var(--brand)]" : "text-muted-foreground"
              }`}
            >
              {row.multiplier}
            </div>
            <div
              className={`px-3 py-2.5 text-xs border-l border-muted text-right tabular-nums ${
                row.highlight
                  ? "text-[var(--brand)] font-bold"
                  : row.bold
                  ? "font-semibold text-foreground"
                  : "text-foreground/90"
              }`}
            >
              {row.annual}
            </div>
          </div>
        ))}

        {/* TOTAL row */}
        <div className="grid grid-cols-[44px_140px_1fr_120px] border-t-2 border-[var(--brand)] bg-accent/40">
          <div className="px-3 py-3" />
          <div className="px-3 py-3 text-sm font-bold text-foreground border-l border-muted">
            Fixed Monthly Investment
          </div>
          <div className="px-3 py-3 border-l border-muted" />
          <div className="px-3 py-3 text-sm font-bold text-[var(--brand)] border-l border-muted text-right tabular-nums">
            $20,000
          </div>
        </div>
      </div>

      {/* ── Strategic Summary ── */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 w-full">
        {SUMMARY.map((item) => (
          <div
            key={item.title}
            className="rounded-xl border border-muted bg-accent/20 p-4 flex flex-col gap-2"
          >
            <div className="flex items-center gap-2 text-[var(--brand)]">
              {item.icon}
              <h3 className="text-xs font-semibold text-foreground">
                {item.title}
              </h3>
            </div>
            <p className="text-[11px] text-muted-foreground leading-relaxed">
              {item.description}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}
